#!/usr/bin/env bash
# GENERATE INDEX.md — the cross-track view of what is claimed and what has landed.
#
#   bash general/tools/index.sh          # write INDEX.md
#   bash general/tools/index.sh --check  # print it, write nothing
#
# WHY THIS IS GENERATED AND NEVER HAND-EDITED
#
# Claims live in each track's launcher, section 3b, so the operator writes ONE document per
# track (WA-L.1). A rollup is still wanted — "how many claims are still UNPROVEN" is the
# real progress measure. But a rollup a person maintains is a SECOND place a claim lives,
# and two places disagree inside a week (WA-P.4). So it is derived, on demand, from the
# launchers and the landed bundles. If it is wrong, the launcher is wrong; fix that.
set -uo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

CHECK=0; [ "${1:-}" = "--check" ] && CHECK=1
OUT="INDEX.md"
TMP="$(mktemp)"

{
  printf '# INDEX — generated, do not edit\n\n'
  printf '_Generated by `bash general/tools/index.sh` on %s. Claims live in each track'"'"'s\n' "$(date +%F)"
  printf 'launcher, section 3b; bundles live in `results/`. If a line here is wrong, the\n'
  printf 'launcher is wrong — fix that and regenerate (WA-P.4)._\n\n'

  printf '## Tracks\n\n'
  if ls launchers/*.md >/dev/null 2>&1; then
    printf '| track | launcher | gates declared | claims declared |\n|---|---|---|---|\n'
    for L in launchers/*.md; do
      t="$(basename "$L" .md | sed 's/^LAUNCHER_//')"
      # A gate row names a stop condition; a claim row carries an UNPROVEN/SUPPORTED/etc.
      ng=$(grep -cE '^\|.*\|.*(SINGLE-PASS|LOOPED).*\|' "$L" 2>/dev/null || echo 0)
      nc=$(grep -cE '^\|[[:space:]]*`?([a-z0-9][a-z0-9_-]*:)?C[0-9]+' "$L" 2>/dev/null || echo 0)
      printf '| %s | `%s` | %s | %s |\n' "$t" "$L" "$ng" "$nc"
    done
  else
    printf '_No launchers yet. A track starts by writing one (WA-L.1)._\n'
  fi

  printf '\n## Claims\n\n'
  if ls launchers/*.md >/dev/null 2>&1; then
    printf '| ID | status | track |\n|---|---|---|\n'
    for L in launchers/*.md; do
      t="$(basename "$L" .md | sed 's/^LAUNCHER_//')"
      grep -E '^\|[[:space:]]*`?([a-z0-9][a-z0-9_-]*:)?C[0-9]+' "$L" 2>/dev/null \
        | while IFS= read -r line; do
            id=$(printf '%s' "$line" | grep -oE '([a-z0-9][a-z0-9_-]*:)?C[0-9]+' | head -1)
            st=$(printf '%s' "$line" | grep -oE 'UNPROVEN|SUPPORTED|REFUTED|WITHDRAWN' | head -1)
            [ -n "$id" ] && printf '| `%s` | %s | %s |\n' "$id" "${st:-—}" "$t"
          done
    done
  fi

  printf '\n## Bundles\n\n'
  if ls -d results/*/ >/dev/null 2>&1; then
    printf '| gate | status | tables | figures | scripts |\n|---|---|---|---|---|\n'
    for B in results/*/; do
      g="$(basename "$B")"
      st=$(grep -m1 -oE '^STATUS:[^—-]*' "$B/README.md" 2>/dev/null | sed 's/STATUS:[[:space:]]*//' | cut -c1-24)
      printf '| `%s` | %s | %s | %s | %s |\n' "$g" "${st:-no STATUS line}" \
        "$(ls "$B"/tables/*.tsv 2>/dev/null | wc -l)" \
        "$(ls "$B"/figures/* 2>/dev/null | wc -l)" \
        "$(ls "$B"/scripts/* 2>/dev/null | wc -l)"
    done
  else
    printf '_No bundles yet. A gate that produced no bundle produced no result (WA-R.5)._\n'
  fi

  printf '\n## Progress\n\n'
  NU=$(grep -hcE 'UNPROVEN' launchers/*.md 2>/dev/null | paste -sd+ | bc 2>/dev/null || echo 0)
  NB=$(ls -1d results/*/ 2>/dev/null | wc -l)
  printf -- '- claims still UNPROVEN: **%s**\n' "${NU:-0}"
  printf -- '- bundles landed: **%s**\n' "$NB"
  printf '\n> Progress is not how much you have done. It is how many claims left UNPROVEN,\n'
  printf '> and whether any went to REFUTED. A refutation is a result.\n'
} > "$TMP"

if [ "$CHECK" = 1 ]; then cat "$TMP"; rm -f "$TMP"; exit 0; fi
mv "$TMP" "$OUT"
echo "wrote $OUT"
