"""
Script inspector for ARIS context.
Generates a compact summary of all Python scripts in MELISSA_SCRIPTS/
showing: functions, docstrings, file I/O patterns, and imports.
Run: python tools/inspect_scripts.py > MELISSA_SCRIPTS/SCRIPTS_SUMMARY.md
"""
import ast
import sys
import os
from pathlib import Path

def extract_string_literals(node):
    """Extract string literals from calls (catches open(), pd.read_csv(), etc.)"""
    strings = []
    for child in ast.walk(node):
        if isinstance(child, ast.Constant) and isinstance(child.s, str):
            if any(ext in child.s for ext in ['.json', '.csv', '.tsv', '.fasta', '.fa', '.txt', '.pkl', '.parquet']):
                strings.append(child.s)
    return strings

def extract_io_patterns(tree):
    """Find file read/write patterns in the AST."""
    reads, writes = [], []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            # open() calls
            if isinstance(func, ast.Name) and func.id == 'open':
                args = node.args
                mode = 'r'
                if len(args) > 1 and isinstance(args[1], ast.Constant):
                    mode = args[1].s
                elif node.keywords:
                    for kw in node.keywords:
                        if kw.arg == 'mode' and isinstance(kw.value, ast.Constant):
                            mode = kw.value.s
                path_strings = extract_string_literals(args[0]) if args else []
                if 'w' in mode or 'a' in mode:
                    writes.extend(path_strings)
                else:
                    reads.extend(path_strings)
            # pandas read functions
            func_str = ''
            if isinstance(func, ast.Attribute):
                func_str = func.attr
            elif isinstance(func, ast.Name):
                func_str = func.id
            if func_str in ('read_csv', 'read_json', 'read_parquet', 'read_jsonl'):
                reads.extend(extract_string_literals(node))
            if func_str in ('to_csv', 'to_json', 'to_parquet', 'savefig'):
                writes.extend(extract_string_literals(node))
    return list(set(reads)), list(set(writes))

def extract_imports(tree):
    imports = []
    for node in tree.body:
        if isinstance(node, ast.Import):
            imports.extend(n.name.split('.')[0] for n in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.append(node.module.split('.')[0])
    return list(set(imports))

def inspect_file(file_path):
    try:
        source = Path(file_path).read_text(encoding='utf-8')
        tree = ast.parse(source)
    except Exception as e:
        return f"  ERROR: {e}\n"

    out = []
    imports = extract_imports(tree)
    reads, writes = extract_io_patterns(tree)

    if imports:
        out.append(f"  **Imports:** {', '.join(sorted(imports))}")
    if reads:
        out.append(f"  **Reads:** {'; '.join(reads[:5])}")
    if writes:
        out.append(f"  **Writes:** {'; '.join(writes[:5])}")

    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            args = [a.arg for a in node.args.args]
            doc = ast.get_docstring(node) or "*(no docstring)*"
            out.append(f"\n  `def {node.name}({', '.join(args)}):`")
            out.append(f"  {doc.splitlines()[0]}")

        elif isinstance(node, ast.ClassDef):
            out.append(f"\n  **Class `{node.name}`:** {ast.get_docstring(node) or ''}")
            for sub in node.body:
                if isinstance(sub, ast.FunctionDef):
                    args = [a.arg for a in sub.args.args]
                    doc = ast.get_docstring(sub) or "*(no docstring)*"
                    out.append(f"    `def {sub.name}({', '.join(args)}):`  {doc.splitlines()[0]}")

    return '\n'.join(out)

def inspect_directory(root_dir, output_file):
    root = Path(root_dir)
    with open(output_file, 'w') as f:
        f.write("# MELISSA_SCRIPTS — Function Summary for ARIS\n\n")
        f.write("> Auto-generated by tools/inspect_scripts.py\n")
        f.write("> Add per-folder notes manually below each `##` header.\n\n")
        f.write("---\n\n")

        for py_file in sorted(root.rglob('*.py')):
            rel = py_file.relative_to(root)
            f.write(f"## `{rel}`\n\n")
            f.write(inspect_file(py_file))
            f.write("\n\n")
            f.write("> **NOTES:** *(add your notes here about what this script does, "
                    "what worked, what didn't, and how ARIS should use it)*\n\n")
            f.write("---\n\n")

    print(f"Written to {output_file}")

if __name__ == "__main__":
    inspect_directory(
        "/home/borg/RESEARCH-in-sleep-RETRON-DB_V3/MELISSA_SCRIPTS/ncRNA_analysis/PREVIOUS_ARIS_WORK",
        "/home/borg/RESEARCH-in-sleep-RETRON-DB_V3/MELISSA_SCRIPTS/ncRNA_analysis/PREVIOUS_ARIS_WORK/Notes.md"
    )
