#!/usr/bin/env bash
# clone_safe.sh — BS-16: a bundle must survive a fresh clone.
#
#   check:        bash general/checks/clone_safe.sh results/<GATE>
#   validate me:  SELFTEST=1 bash general/checks/clone_safe.sh
#
# WHY THIS EXISTS
#
# BS-11 hashes every file present in a bundle at seal time and then demands that file
# forever. It never asks whether the file will still be there. On 2026-09-10 five of six
# bundles in this project were found listing `scripts/__pycache__/*.pyc` in OUTPUTS.tsv —
# regenerated bytecode, matched by .gitignore, never committed. Each of those bundles
# passes bundle_valid.sh in the tree that built it and fails BS-11 on every clone, and
# BS-6 makes a landed bundle write-once, so the failure is permanent.
#
# The defect was invisible because every check measured the directory as it happened to
# be, instead of the artifact a later reader will actually get. This asks that question
# directly, in milliseconds, with no input hashing.
#
# WHAT IT CHECKS
#
#   1. No OUTPUTS.tsv row is matched by .gitignore. An ignored path is never committed,
#      so it vanishes on clone and BS-11 fails there forever.
#   2. No bundle file is a non-regular file. A character device, socket or fifo inside a
#      bundle is never real evidence: git cannot carry it, and its presence means
#      something mounted into the directory. (Claude Code materialises .claude/ and
#      .mcp.json as device nodes in whatever directory becomes a session's cwd — which is
#      why a session must never `cd` into results/<GATE>/.)
#
# WHAT IT DELIBERATELY DOES NOT CHECK
#
# Whether the files are *tracked*. Before the bundle's commit nothing is tracked yet, and
# the check has to be usable at exactly that moment — before the commit, which is the only
# point where the defect is still cheap to fix. Ignored-ness is the cause; tracked-ness is
# a consequence that arrives too late to act on.
set -uo pipefail

# --------------------------------------------------------------------------
if [ "${SELFTEST:-0}" = "1" ]; then
  export SELFTEST=0
  ME="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
  T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
  git -C "$T" init -q .
  printf '__pycache__/\n' > "$T/.gitignore"
  B="$T/results/g-test"; mkdir -p "$B/scripts/__pycache__" "$B/tables"
  echo 'print(1)' > "$B/scripts/s1.py"
  echo 'data'     > "$B/tables/t1.tsv"

  pass=0; fail=0
  expect() { # $1 accept|reject  $2 label
    if bash "$ME" "$B" >/dev/null 2>&1; then r=accept; else r=reject; fi
    if [ "$r" = "$1" ]; then pass=$((pass+1)); echo "  ok   $2"
    else fail=$((fail+1)); echo "  FAIL $2 (got $r, wanted $1)"; fi
  }

  { printf 'path\tsha256\tbytes\n'
    printf 'scripts/s1.py\tx\t9\n'
    printf 'tables/t1.tsv\tx\t5\n'; } > "$B/OUTPUTS.tsv"
  expect accept "a bundle listing only committable files"

  : > "$B/scripts/__pycache__/s1.cpython-312.pyc"
  printf 'scripts/__pycache__/s1.cpython-312.pyc\tx\t1\n' >> "$B/OUTPUTS.tsv"
  expect reject "an OUTPUTS.tsv row matched by .gitignore"

  echo "selftest: $pass passed, $fail failed"
  [ "$fail" -eq 0 ]; exit $?
fi
# --------------------------------------------------------------------------

B="${1:-}"
[ -n "$B" ] || { echo "usage: clone_safe.sh results/<GATE>"; exit 2; }
B="${B%/}"
[ -d "$B" ] || { echo "clone_safe: no such bundle: $B"; exit 2; }
[ -f "$B/OUTPUTS.tsv" ] || { echo "clone_safe: $B has no OUTPUTS.tsv (not sealed yet)"; exit 2; }

fail=0

# 1 — no listed row may be gitignored.
while IFS= read -r f; do
  [ -z "$f" ] && continue
  if git -C "$B" check-ignore -q -- "$f" 2>/dev/null; then
    echo "NOT CLONE-SAFE: OUTPUTS.tsv lists an ignored path: $f"
    fail=1
  fi
done < <(awk -F'\t' 'NR>1{print $1}' "$B/OUTPUTS.tsv")

# 2 — no non-regular file anywhere in the bundle.
while IFS= read -r f; do
  [ -z "$f" ] && continue
  echo "NOT CLONE-SAFE: not a regular file (mounted into the bundle?): $f"
  fail=1
done < <(cd "$B" && find . ! -type d ! -type f -printf '%P\n' 2>/dev/null | sort)

if [ "$fail" -eq 0 ]; then
  echo "OK: $B is clone-safe — every OUTPUTS.tsv row is committable, no mounted files."
else
  echo ""
  echo "  Fix BEFORE the bundle is committed: remove the offending paths, then"
  echo "    bash general/checks/bundle_valid.sh --write-outputs $B"
  echo "  After the commit, BS-6 makes the bundle write-once and this costs a"
  echo "  correction bundle instead of one command."
fi
exit $fail
